export const NEWS_DATA = {
  newsList: [
    {
      title: 'News 1',
      description: 'asd asd a das d asd asd as da d',
      imageUrls: 'https://picsum.photos/200/300',
      newType: 'Business',
    },
    {
      title: 'News 2',
      description: 'Description 2',
      imageUrls: 'https://picsum.photos/200/300',
      newType: 'Entertainment',
    },
    {
      title: 'News 3',
      description: 'Description 3',
      imageUrls: 'https://picsum.photos/200/300',
      newType: 'General',
    },
    {
      title: 'News 1',
      description: 'Description 1',
      imageUrls: 'https://picsum.photos/200/300',
      newType: 'Business',
    },
    {
      title: 'News 2',
      description: 'Description 2',
      imageUrls: 'https://picsum.photos/200/300',
      newType: 'Entertainment',
    },
    {
      title: 'News 3',
      description: 'Description 3',
      imageUrls: 'https://picsum.photos/200/300',
      newType: 'General',
    },
    {
      title: 'News 1',
      description: 'Description 1',
      imageUrls: 'https://picsum.photos/200/300',
      newType: 'Business',
    },
    {
      title: 'News 2',
      description: 'Description 2',
      imageUrls: 'https://picsum.photos/200/300',
      newType: 'Entertainment',
    },
    {
      title: 'News 3',
      description: 'Description 3',
      imageUrls: 'https://picsum.photos/200/300',
      newType: 'General',
    },
    {
      title: 'News 1',
      description: 'Description 1',
      imageUrls: 'https://picsum.photos/200/300',
      newType: 'Business',
    },
    {
      title: 'News 2',
      description: 'Description 2',
      imageUrls: 'https://picsum.photos/200/300',
      newType: 'Entertainment',
    },
    {
      title: 'News 3',
      description: 'Description 3',
      imageUrls: 'https://picsum.photos/200/300',
      newType: 'General',
    },
    {
      title: 'News 1',
      description: 'Description 1',
      imageUrls: 'https://picsum.photos/200/300',
      newType: 'Business',
    },
    {
      title: 'News 2',
      description: 'Description 2',
      imageUrls: 'https://picsum.photos/200/300',
      newType: 'Entertainment',
    },
    {
      title: 'News 3',
      description: 'Description 3',
      imageUrls: 'https://picsum.photos/200/300',
      newType: 'General',
    },
    {
      title: 'News 1',
      description: 'Description 1',
      imageUrls: 'https://picsum.photos/200/300',
      newType: 'Business',
    },
    {
      title: 'News 2',
      description: 'Description 2',
      imageUrls: 'https://picsum.photos/200/300',
      newType: 'Entertainment',
    },
    {
      title: 'News 3',
      description: 'Description 3',
      imageUrls: 'https://picsum.photos/200/300',
      newType: 'General',
    },
    {
      title: 'News 1',
      description: 'Description 1',
      imageUrls: 'https://picsum.photos/200/300',
      newType: 'Business',
    },
    {
      title: 'News 2',
      description: 'Description 2',
      imageUrls: 'https://picsum.photos/200/300',
      newType: 'Entertainment',
    },
    {
      title: 'News 3',
      description: 'Description 3',
      imageUrls: 'https://picsum.photos/200/300',
      newType: 'General',
    },
  ],
  filters: [
    'All',
    'Business',
    'Entertainment',
    'General',
    'Health',
    'Science',
    'Sports',
    'Technology',
  ],
};
